spring:
  redis:
    host: *****************
    port: 6363
    password: 'flos1q2w3e4r'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://*****************:3306/flosdev
    username: dev
    password: test1234
  jpa:
    hibernate:
      ddl-auto: none
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:import.sql
  security:
    oauth2:
      client:
        registration:
          naver:
            redirectUri: "https://*****************/api/login/oauth2/code/naver"
          kakao:
            redirectUri: "https://*****************/api/login/oauth2/code/kakao"
file:
  dir: /home/ubuntu/flos/